generator:
  max-text-length: int
  graph:
    order: int
    path: path/file.json

logging:
  basic-config:
    filename: path/file.log
    level: str

telegram-bot:
  admin-ids:
    - int

  temp-path: path/dir

  updater:
    token: str
